### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by salmanulfarzy** [salmanulfarzy/salmanulfarzy.github.io#1]
https://alexpeattie.com/blog/better-syntax-highlighting-with-rouge

![image](https://cloud.githubusercontent.com/assets/10276208/25895794/115857c2-359f-11e7-9c18-60dbcea2a1d0.png)

**Comment by sfarzy** [comment]
https://gist.github.com/sfarzy/75654a6cced886f1206be142143f45c1

![aphyr](https://cloud.githubusercontent.com/assets/10276208/24829198/072daeec-1c5d-11e7-8616-53348b3fec7b.png)

**Comment by sfarzy** [comment]
What's your take on line numbers ?
